#docker-composeのバージョン
version: '3'
services:
  db:
    image: mysql:8.0
    ports:
      - '3306:3306' # ホストからゲストへポートフォワード
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: Kyo-Ron_development
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: ron
      MYSQL_PASSWORD: tenten2
    volumes:
      - mysql-data:/var/lib/mysql #削除してもdbのデータが消えなくなる

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: dockerize -wait tcp://db:3306 -timeout 20s bundle exec rails s -p 3000 -b '0.0.0.0'
    tty: true
    stdin_open: true
    depends_on:
      - db # DB側のコンテナが出来上がってからwebを実行する
      - chrome
    ports:
      - "3000:3000" # ホストからゲストへポートフォワード
    volumes:
      - .:/Kyo-Ron:cached # ソースコード変更したらDocker側も即反映されるように
      - tmp-data:/Kyo-Ron/tmp/sockets #ソケット通信用ファイルをnginxコンテナと共有
      - public-data:/Kyo-Ron/public #画像データとかをnginxと共有
  chrome:
    image: selenium/standalone-chrome:latest
    ports:
      - 4444:4444

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    restart: always #明示的にstopさせるまでリスタートする。（失敗するたび遅延あり）
    volumes:
      - tmp-data:/Kyo-Ron/tmp/sockets
      - public-data:/Kyo-Ron/public
    depends_on:
      - web

volumes:
  public-data:
  tmp-data:
  mysql-data:

