# version: 2.1 # CircleCIのバージョンのこと

# orbs:
#   ruby: circleci/ruby@1.1.2

# jobs: # 実行処理の単位
#   build:
#     docker: # DockerでRubyのイメージを作成。Dockerfileとversionを合わせる。
#       - image: circleci/ruby:2.6.6
#     working_directory: ~/Kyo-Ron
#     steps:
#       - checkout: #gitリポジトリからソースコードをcheckout
#           path: ~/Kyo-Ron
#       - ruby/install-deps #bundle install

#   test:
#     docker:
#       - image: circleci/ruby:2.6.6
#       - image: circleci/mysql:5.5
#         environment:
#           MYSQL_DATABASE: Kyo-Ron_test
#           MYSQL_ROOT_PASSWORD: password
#           MYSQL_USER: ron
#           MYSQL_PASSWORD: tenten2
#     environment:
#       BUNDLE_JOBS: "3"
#       BUNDLE_RETRY: "3"
#       APP_DATABASE_HOST: "127.0.0.1" #自分のCPという意味
#       RAILS_ENV: test
#     working_directory: ~/Kyo-Ron
#     steps:
#       - checkout:
#           path: ~/Kyo-Ron
#       - run:
#           name: docker-compose up
#           command: docker-compose up -d

#       - ruby/install-deps #bundle install
#       - run:
#           name: yarn Install
#           command: yarn install
#       - run:
#           name: Database setup
#           command: bundle exec rails db:migrate
#       - run:
#           name: RSpec
#           command: bundle exec rspec

# workflows:
#   version: 2
#   build_test:
#     jobs:
#       - build
#       - test:
#           requires:
#             - build #buildが終わってから実行。
version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: docker-compose up
          command: |
            set -x
            docker-compose up --build -d
      - run:
          name: docker-compose stop
          command: |
            set -x
            docker-compose stop
      - run:
          name: docker-compose up
          command: |
            set -x
            docker-compose up -d
      - run:
          name: test
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob 'spec/**/*_spec.rb' | circleci tests split --split-by=timings)"
            docker-compose run web rspec --format progress \
                                                                  --format RspecJunitFormatter \
                                                                  --out /tmp/test-results/rspec.xml \
                                                                  $TEST_FILES
      - run:
          name: docker-compose down
          command: docker-compose down
